// Install/uninstall the daemon as a per-user autostart on Windows.
// Drops a .bat into the Startup folder that runs `call-me-skill daemon start`
// on every login. No admin rights needed, no Task Scheduler XML.
import { existsSync, mkdirSync, writeFileSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';

const STARTUP_DIR = join(
  homedir(),
  'AppData', 'Roaming', 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup'
);
const BAT_FILE = join(STARTUP_DIR, 'call-me-skill-daemon.bat');

const BAT_CONTENT = `@echo off
REM Auto-generated by call-me-skill setup.
REM Starts the hotkey daemon at user login. Delete this file to disable.
call-me-skill daemon start >nul 2>&1
`;

export function isAutostartInstalled() {
  return existsSync(BAT_FILE);
}

export function installAutostart() {
  if (!existsSync(STARTUP_DIR)) mkdirSync(STARTUP_DIR, { recursive: true });
  writeFileSync(BAT_FILE, BAT_CONTENT);
  return BAT_FILE;
}

export function uninstallAutostart() {
  if (existsSync(BAT_FILE)) {
    unlinkSync(BAT_FILE);
    return true;
  }
  return false;
}

export function autostartPath() {
  return BAT_FILE;
}
